kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: swisnap-agent-k8s
  namespace: kube-system
  labels:
    app: swisnap-agent-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swisnap-agent-k8s
  template:
    metadata:
      labels:
        app: swisnap-agent-k8s
    spec:
      serviceAccountName: swisnap-agent-serviceaccount
      containers:
        - name: swisnap-agent-k8s
          image: 'solarwinds/solarwinds-snap-agent-docker:1.0.1'
          imagePullPolicy: Always
          env:
            - name: APPOPTICS_TOKEN
              value: 'APPOPTICS_TOKEN'
            - name: SWISNAP_ENABLE_APACHE
              value: 'false'
            - name: SWISNAP_ENABLE_DOCKER
              value: 'false'
            - name: SWISNAP_ENABLE_ELASTICSEARCH
              value: 'false'
            - name: SWISNAP_ENABLE_KUBERNETES
              value: 'true'
            - name: SWISNAP_ENABLE_MESOS
              value: 'false'
            - name: SWISNAP_ENABLE_MONGODB
              value: 'false'
            - name: SWISNAP_ENABLE_MYSQL
              value: 'false'
            - name: SWISNAP_ENABLE_RABBITMQ
              value: 'false'
            - name: SWISNAP_ENABLE_STATSD
              value: 'false'
            - name: SWISNAP_ENABLE_ZOOKEEPER
              value: 'false'
            - name: SWISNAP_DISABLE_HOSTAGENT
              value: 'true'
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
