---
# log_level for the Snap daemon. Supported values are
# trace, debug, info, warning, error, fatal, panic
# Default value is warning
#log_level: debug
log_format: text

control:
  # Configuration auto_discover_path sets the directory(s) to auto load plugins and tasks on
  # the start of the snap daemon. This can be a colon separated list of directories.
  auto_discover_path: /opt/SolarWinds/Snap/autoload

  # Configuration plugin_trust_level sets the plugin trust level for swisnapd. The default state
  # for plugin trust level is enabled (1). When enabled, only signed plugins that can
  # be verified will be loaded into swisnapd. Signatures are verified from
  # keyring files specified in keyring_path. Plugin trust can be disabled (0) which
  # will allow loading of all plugins whether signed or not. The warning state allows
  # for loading of signed and unsigned plugins. Warning messages will be displayed if
  # an unsigned plugin is loaded. Any signed plugins that cannot be verified will
  # not be loaded. Valid values are 0 - Off, 1 - Enabled, 2 - Warning
  plugin_trust_level: 0

  # Configuration plugin_load_timeout sets the maximal time allowed for a plugin to load.
  # Some plugins may require more time to initialize.
  # Default value is 5
  plugin_load_timeout: 15

  # The bind address and port the agent uses to control and receive data from plugins.
  # The default address is 127.0.0.1 and the default port is 21414.
  #listen_addr: 127.0.0.1
  #listen_port: 21414

  # Configuration temp_dir_path sets the temporary directory which houses the temporary files
  temp_dir_path: /tmp/SolarWinds/Snap

  # temp_dir_enable sets whether the application startup leverage the `temp_path_dir` to start
  # plugins. The use of the temporary location is considered legacy functionality, so
  # set this boolean to `true` if you'd like to use it
  #temp_dir_enable: true

  # Search path for load: directives in plugin configuration
  plugin_path: /opt/SolarWinds/Snap/bin
  task_path: /opt/SolarWinds/Snap/etc/tasks.d

  # Plugins section contains plugin config settings that will be applied for plugins across tasks.
  plugins:
    include: /opt/SolarWinds/Snap/etc/plugins.d
    publisher:
      publisher-appoptics:
        all:
          token: APPOPTICS_TOKEN
          url: "https://api.appoptics.com/v1/measurements"
          # Set this option if you want a different "host" tag to be associated with the metrics you report.
          # hostname_alias: myhostname
          #
          # Enable support for HTTP proxy.
          # proxy_url: "http://<proxy-server-ip>:<port>"
          # When HTTP proxy requires user authentication, uncomment the following lines and update username and password.
          # proxy_user:<username>
          # proxy_password:<password>
          #
          # Enable support for SOCKS5 proxy. Only SOCKS5 proxies are supported at this time.
          # When SOCKS5 proxy requires user authentication, uncomment the following lines and update username and password.
          # proxy_url: "socks5://<proxy-server-ip>:<port>"
          # proxy_user:<username>
          # proxy_password:<password>

          # grpc_timeout sets the maximum time allowed for a gRPC call.
          # Some collector or plublisher plugins require more time to finish a gRPC method call during collection or publishing.
          # When grpc_timeout is increased, then the deadline specified in manifest task file should also be increased to allow
          # more time for the task to finish all associated jobs. The deadline specifies the maximum time allowed to finish all
          # the associated task's jobs (like collection and publishing of the metrics) which now can take longer.
          # Default value is 10
          grpc_timeout: 30

          # ec2_check_timeout allows to configure timeout for querying EC2 instance metadata URL to determine if host agent
          # is running on EC2 (or OpenStack) instance. By default it is set to 1s.
          # ec2_check_timeout: "1s"

      publisher-processes:
        all:
          token: APPOPTICS_TOKEN
          url: "https://api.appoptics.com/v1/agent/report"

    collector:
      aosystem:
        all:
          # grpc_timeout sets the maximum time allowed for a gRPC call.
          # Some collector or plublisher plugins require more time to finish a gRPC method call during collection or publishing.
          # When grpc_timeout is increased, then the deadline specified in manifest task file should also be increased to allow
          # more time for the task to finish all associated jobs. The deadline specifies the maximum time allowed to finish all
          # the associated task's jobs (like collection and publishing of the metrics) which now can take longer.
          # Default value is 10
          grpc_timeout: 30

  # Tags that will be applied to collected metrics across tasks.
  tags:
   # tags all metrics
   #/:
   #  environment: production
   # tags a specific metric namespace
   #/nginx:
   #  site: mysite.com
